//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityOrnek
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbOgrenciSinavEntities1 : DbContext
    {
        public DbOgrenciSinavEntities1()
            : base("name=DbOgrenciSinavEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<Notlar> Notlar { get; set; }
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
    
        public virtual ObjectResult<NotListe_Result> NotListe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotListe_Result>("NotListe");
        }
    
        public virtual ObjectResult<NotListe2_Result> NotListe2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotListe2_Result>("NotListe2");
        }
    }
}
